version: 2.1
workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d{4}\.\d+$/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d{4}\.\d+$/
jobs:
  build:
    docker:
      - image: cibuilds/chrome-extension:latest
    steps:
      - checkout
      - run:
          name: "Prepare Extension For Production"
          command: |
            if [[ $CIRCLE_TAG != "" ]];then
              echo "Applying real version."
              jq '.version = env.CIRCLE_TAG' manifest.json | sponge manifest.json
            fi
            jq '.browser_action.default_icon = "icon.png"' manifest.json | sponge manifest.json
      - run:
          name: "Filler - Proper CI/CD needs to be implemented."
          command: echo "The start of our build process."
      - run: apk add --no-cache zip
      - run:
          name: "Package Extension"
          command: zip -r pointless.zip . -x *.git*
      - persist_to_workspace:
          root: /root/project
          paths:
            - pointless.zip
  publish:
    docker:
      - image: cibuilds/chrome-extension:latest
    environment:
      - APP_ID: edmkpfdmophaaeedepooedlhioimljai
    steps:
      - attach_workspace:
          at: /root/workspace
      - store_artifacts:
          path: "/root/workspace/pointless.zip"
      - run:
          name: "Publish to the Google Chrome Store"
          command: publish /root/workspace/pointless.zip
