version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: "Filler - Proper CI/CD needs to be implemented."
          command: echo "The start of our build process."
